name: Docker Build

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
    - main2
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the repo  directory
      uses: actions/checkout@v2
    - name: Install bazel
      run: |
        wget  https://github.com/bazelbuild/bazel/releases/download/6.1.1/bazel-6.1.1-installer-linux-x86_64.sh
        sudo bash bazel-6.1.1-installer-linux-x86_64.sh

    - name: Which Bazel
      run: |
        which bazel
        bazel version

    - name: Run bazel build
      run:
        bazel build //examples/cpp/helloworld:all
